version: '3.8'
services:
  # 1. Identity Database (Relational)
  postgres:
    image: postgres:15
    container_name: connect_postgres
    environment:
      POSTGRES_DB: connect_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  # 2. Chat History Database (Document)
  mongo:
    image: mongo:6.0
    container_name: connect_mongo
    ports:
      - "27017:27017"

  # 3. Message Broker Coordinator
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: connect_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 4. Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: connect_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
