spring.application.name=chat-service

server.port=8082

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/connect_chat

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=chat-group
spring.kafka.consumer.auto-offset-reset=earliest
